# Generated by Django 4.2.6 on 2023-11-14 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_task_accepted_date_task_done_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='done_date',
            new_name='completed_date',
        ),
    ]
