# Generated by Django 4.2.6 on 2023-11-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_rename_done_date_task_completed_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='accepted_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='completed_date',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed')], default='pending', max_length=50),
        ),
    ]
