# Generated by Django 4.2.7 on 2023-11-16 17:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0007_remove_task_assigned_to_task_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_by',
            field=models.ManyToManyField(related_name='completed_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
