# Generated by Django 4.2.7 on 2023-11-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_task_completed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='accepted_by_engineer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='accepted_by_supervisor',
            field=models.BooleanField(default=False),
        ),
    ]
