# Generated by Django 4.2.7 on 2023-11-19 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0013_productionissue_accepted_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionissue',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_issues', to=settings.AUTH_USER_MODEL),
        ),
    ]
