# Generated by Django 4.2.6 on 2023-11-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0014_productionissue_accepted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionissue',
            name='line',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productionissue',
            name='machine',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productionissue',
            name='team',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
