# Generated by Django 4.2.6 on 2023-11-20 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0015_productionissue_line_productionissue_machine_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productionissue',
            old_name='team',
            new_name='type_of_issue',
        ),
    ]
