# Generated by Django 4.2.7 on 2023-11-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0016_rename_team_productionissue_type_of_issue'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueFix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.TextField(verbose_name='Przyczyna')),
                ('action', models.TextField(verbose_name='Co zrobiłeś, żeby naprawić')),
            ],
        ),
        migrations.AlterField(
            model_name='productionissue',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
