# Generated by Django 4.2.6 on 2023-11-29 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0020_alter_task_assigned_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
