# Generated by Django 4.2.7 on 2023-11-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_task_completed_by'),
        ('accounts', '0002_profile_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='supervised_tasks',
            field=models.ManyToManyField(related_name='supervisors', to='user_profile.task'),
        ),
    ]
