# Generated by Django 4.2.7 on 2023-11-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_supervised_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('engineer', 'Engineer'), ('user', 'User'), ('supervisor', 'Supervisor')], max_length=50),
        ),
    ]
