# Generated by Django 4.2.7 on 2023-11-16 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='supervised_tasks',
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('engineer', 'Engineer'), ('user', 'User'), ('production', 'Production')], max_length=50),
        ),
    ]
